// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: characters.proto

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CharactersServiceClient is the client API for CharactersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CharactersServiceClient interface {
	GetAllGenders(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Genders, error)
	GetAllRealms(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Realms, error)
	GetAllCharacters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Characters, error)
	GetAllCharactersForUser(ctx context.Context, in *UserTarget, opts ...grpc.CallOption) (*Characters, error)
	GetCharacter(ctx context.Context, in *CharacterTarget, opts ...grpc.CallOption) (*Character, error)
	CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*Character, error)
	DeleteCharacter(ctx context.Context, in *Character, opts ...grpc.CallOption) (*empty.Empty, error)
	EditCharacter(ctx context.Context, in *Character, opts ...grpc.CallOption) (*Character, error)
	// Adds the given amount of playtime to the character and returns the total playtime
	AddCharacterPlayTime(ctx context.Context, in *PlayTimeMessage, opts ...grpc.CallOption) (*PlayTimeMessage, error)
}

type charactersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCharactersServiceClient(cc grpc.ClientConnInterface) CharactersServiceClient {
	return &charactersServiceClient{cc}
}

func (c *charactersServiceClient) GetAllGenders(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Genders, error) {
	out := new(Genders)
	err := c.cc.Invoke(ctx, "/sro.characters.CharactersService/GetAllGenders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *charactersServiceClient) GetAllRealms(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Realms, error) {
	out := new(Realms)
	err := c.cc.Invoke(ctx, "/sro.characters.CharactersService/GetAllRealms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *charactersServiceClient) GetAllCharacters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Characters, error) {
	out := new(Characters)
	err := c.cc.Invoke(ctx, "/sro.characters.CharactersService/GetAllCharacters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *charactersServiceClient) GetAllCharactersForUser(ctx context.Context, in *UserTarget, opts ...grpc.CallOption) (*Characters, error) {
	out := new(Characters)
	err := c.cc.Invoke(ctx, "/sro.characters.CharactersService/GetAllCharactersForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *charactersServiceClient) GetCharacter(ctx context.Context, in *CharacterTarget, opts ...grpc.CallOption) (*Character, error) {
	out := new(Character)
	err := c.cc.Invoke(ctx, "/sro.characters.CharactersService/GetCharacter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *charactersServiceClient) CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*Character, error) {
	out := new(Character)
	err := c.cc.Invoke(ctx, "/sro.characters.CharactersService/CreateCharacter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *charactersServiceClient) DeleteCharacter(ctx context.Context, in *Character, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/sro.characters.CharactersService/DeleteCharacter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *charactersServiceClient) EditCharacter(ctx context.Context, in *Character, opts ...grpc.CallOption) (*Character, error) {
	out := new(Character)
	err := c.cc.Invoke(ctx, "/sro.characters.CharactersService/EditCharacter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *charactersServiceClient) AddCharacterPlayTime(ctx context.Context, in *PlayTimeMessage, opts ...grpc.CallOption) (*PlayTimeMessage, error) {
	out := new(PlayTimeMessage)
	err := c.cc.Invoke(ctx, "/sro.characters.CharactersService/AddCharacterPlayTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CharactersServiceServer is the server API for CharactersService service.
// All implementations must embed UnimplementedCharactersServiceServer
// for forward compatibility
type CharactersServiceServer interface {
	GetAllGenders(context.Context, *empty.Empty) (*Genders, error)
	GetAllRealms(context.Context, *empty.Empty) (*Realms, error)
	GetAllCharacters(context.Context, *empty.Empty) (*Characters, error)
	GetAllCharactersForUser(context.Context, *UserTarget) (*Characters, error)
	GetCharacter(context.Context, *CharacterTarget) (*Character, error)
	CreateCharacter(context.Context, *CreateCharacterRequest) (*Character, error)
	DeleteCharacter(context.Context, *Character) (*empty.Empty, error)
	EditCharacter(context.Context, *Character) (*Character, error)
	// Adds the given amount of playtime to the character and returns the total playtime
	AddCharacterPlayTime(context.Context, *PlayTimeMessage) (*PlayTimeMessage, error)
	mustEmbedUnimplementedCharactersServiceServer()
}

// UnimplementedCharactersServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCharactersServiceServer struct {
}

func (UnimplementedCharactersServiceServer) GetAllGenders(context.Context, *empty.Empty) (*Genders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllGenders not implemented")
}
func (UnimplementedCharactersServiceServer) GetAllRealms(context.Context, *empty.Empty) (*Realms, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRealms not implemented")
}
func (UnimplementedCharactersServiceServer) GetAllCharacters(context.Context, *empty.Empty) (*Characters, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCharacters not implemented")
}
func (UnimplementedCharactersServiceServer) GetAllCharactersForUser(context.Context, *UserTarget) (*Characters, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCharactersForUser not implemented")
}
func (UnimplementedCharactersServiceServer) GetCharacter(context.Context, *CharacterTarget) (*Character, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCharacter not implemented")
}
func (UnimplementedCharactersServiceServer) CreateCharacter(context.Context, *CreateCharacterRequest) (*Character, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCharacter not implemented")
}
func (UnimplementedCharactersServiceServer) DeleteCharacter(context.Context, *Character) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCharacter not implemented")
}
func (UnimplementedCharactersServiceServer) EditCharacter(context.Context, *Character) (*Character, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCharacter not implemented")
}
func (UnimplementedCharactersServiceServer) AddCharacterPlayTime(context.Context, *PlayTimeMessage) (*PlayTimeMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCharacterPlayTime not implemented")
}
func (UnimplementedCharactersServiceServer) mustEmbedUnimplementedCharactersServiceServer() {}

// UnsafeCharactersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CharactersServiceServer will
// result in compilation errors.
type UnsafeCharactersServiceServer interface {
	mustEmbedUnimplementedCharactersServiceServer()
}

func RegisterCharactersServiceServer(s grpc.ServiceRegistrar, srv CharactersServiceServer) {
	s.RegisterService(&CharactersService_ServiceDesc, srv)
}

func _CharactersService_GetAllGenders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharactersServiceServer).GetAllGenders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sro.characters.CharactersService/GetAllGenders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharactersServiceServer).GetAllGenders(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharactersService_GetAllRealms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharactersServiceServer).GetAllRealms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sro.characters.CharactersService/GetAllRealms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharactersServiceServer).GetAllRealms(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharactersService_GetAllCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharactersServiceServer).GetAllCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sro.characters.CharactersService/GetAllCharacters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharactersServiceServer).GetAllCharacters(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharactersService_GetAllCharactersForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTarget)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharactersServiceServer).GetAllCharactersForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sro.characters.CharactersService/GetAllCharactersForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharactersServiceServer).GetAllCharactersForUser(ctx, req.(*UserTarget))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharactersService_GetCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CharacterTarget)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharactersServiceServer).GetCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sro.characters.CharactersService/GetCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharactersServiceServer).GetCharacter(ctx, req.(*CharacterTarget))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharactersService_CreateCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharactersServiceServer).CreateCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sro.characters.CharactersService/CreateCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharactersServiceServer).CreateCharacter(ctx, req.(*CreateCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharactersService_DeleteCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Character)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharactersServiceServer).DeleteCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sro.characters.CharactersService/DeleteCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharactersServiceServer).DeleteCharacter(ctx, req.(*Character))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharactersService_EditCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Character)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharactersServiceServer).EditCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sro.characters.CharactersService/EditCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharactersServiceServer).EditCharacter(ctx, req.(*Character))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharactersService_AddCharacterPlayTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayTimeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharactersServiceServer).AddCharacterPlayTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sro.characters.CharactersService/AddCharacterPlayTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharactersServiceServer).AddCharacterPlayTime(ctx, req.(*PlayTimeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// CharactersService_ServiceDesc is the grpc.ServiceDesc for CharactersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CharactersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sro.characters.CharactersService",
	HandlerType: (*CharactersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllGenders",
			Handler:    _CharactersService_GetAllGenders_Handler,
		},
		{
			MethodName: "GetAllRealms",
			Handler:    _CharactersService_GetAllRealms_Handler,
		},
		{
			MethodName: "GetAllCharacters",
			Handler:    _CharactersService_GetAllCharacters_Handler,
		},
		{
			MethodName: "GetAllCharactersForUser",
			Handler:    _CharactersService_GetAllCharactersForUser_Handler,
		},
		{
			MethodName: "GetCharacter",
			Handler:    _CharactersService_GetCharacter_Handler,
		},
		{
			MethodName: "CreateCharacter",
			Handler:    _CharactersService_CreateCharacter_Handler,
		},
		{
			MethodName: "DeleteCharacter",
			Handler:    _CharactersService_DeleteCharacter_Handler,
		},
		{
			MethodName: "EditCharacter",
			Handler:    _CharactersService_EditCharacter_Handler,
		},
		{
			MethodName: "AddCharacterPlayTime",
			Handler:    _CharactersService_AddCharacterPlayTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "characters.proto",
}
